modLoader = "javafml"
loaderVersion = "[38,)"
issueTrackerURL = "https://github.com/MoonflowerTeam/${repo}/issues"
license = "GPLv3"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "Moonflower"
credits = "Mista Jub, Jackson"
description = "An expansion on Minecraft's classic music."
displayURL = "https://mistajub.bandcamp.com/album/anchor"
logoFile = "logo.png"

[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "pollen"
mandatory = true
versionRange = "[1.0.0,)"
ordering = "BEFORE"
side = "BOTH"